modified compose and workflow files

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,7 +50,10 @@ jobs:
 
         run: |
           rm -rf ~/docker-compose.yml
+          rm -rf ~/docker-stack.yml
+          
           scp -o StrictHostKeyChecking=no -i ~/ec2-key.pem docker-compose.yml ubuntu@${{ secrets.EC2_HOST }}:~/docker-compose.yml
+          scp -o StrictHostKeyChecking=no -i ~/ec2-key.pem docker-stack.yml ubuntu@${{ secrets.EC2_HOST }}:~/docker-stack.yml
           ssh -o StrictHostKeyChecking=no -i ~/ec2-key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
           
           # Install Docker if not
@@ -78,15 +81,43 @@ jobs:
           # Give docker permissions
           sudo usermod -aG docker ubuntu && newgrp docker
           
-          # Pulling the image
+          # Ensure Docker is running
+          sudo systemctl start docker
+          sudo systemctl enable docker
+
+          # Leave Docker Swarm and Clean Up
+          docker stack rm joke_generator || true
+          docker service rm \$(docker service ls -q) || true
+          docker swarm leave --force || true
+          docker system prune -f --volumes || true
+          
+          # Initialize Docker Swarm if it's not already initialized
+          docker swarm init || true
+          
           export DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
+          
+          # Pull the latest image from Docker Hub
           docker pull \$DOCKER_HUB_USERNAME/jokegenerator-web:latest
           
-          # Running the containers
-          docker-compose -f ~/docker-compose.yml up 
+          # Remove any existing stack
+          docker stack rm joke_generator || true
+          docker system prune -f
+          
+          # Deploy the docker stack
+          docker stack deploy -c ~/docker-stack.yml joke_generator
+          
+          #Checking swarm status
+          docker stack services joke_generator
+          
+          # Checking service logs for debugging
+          docker service logs joke_generator
+
+          # Optionally, check the Docker Compose configuration
+          docker-compose -f ~/docker-compose.yml config
+
+          # Optionally, check the Docker Compose version
+          docker-compose --version
           
           EOF
-          
-
 
 
